name: NixOS VM Regression Tests

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run flake checks
        run: nix build .#tests --print-build-logs
      
